### ISSUE TITLE
Is the repo missing the environment file?

### ISSUE THREAD

**Issue by jpace7** [JunshengFu/autonomous-driving-lane-departure-warning#2]
I am looking for the .yml file?
for the Anaconda environment

**Comment by JunshengFu** [comment]
If you go into the link at **2. Dependencies & my environment**, then you could find them.
For your convenience, this is the yml file with enabled GPU version: https://github.com/udacity/CarND-Term1-Starter-Kit/blob/master/environment-gpu.yml

**Comment by jpace7** [comment]
Thanks for the help!
